BUNDLE_NAME = AprilPrefs

AprilPrefs_FILES = APPAnimatedTitleView.m AprilVC.m
AprilPrefs_CFLAGS = -fobjc-arc
AprilPrefs_LIBRARIES = gcuniversal
AprilPrefs_FRAMEWORKS = UIKit
AprilPrefs_PRIVATE_FRAMEWORKS = Preferences OnBoardingKit
AprilPrefs_INSTALL_PATH = /Library/PreferenceBundles

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk