include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = AprilPrefs

AprilPrefs_FILES = APRRootListController.m APPAnimatedTitleView.m
AprilPrefs_FRAMEWORKS = UIKit
AprilPrefs_PRIVATE_FRAMEWORKS = Preferences OnBoardingKit
AprilPrefs_INSTALL_PATH = /Library/PreferenceBundles
AprilPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk